### ISSUE TITLE
No gpu with index 0

### ISSUE THREAD

**Issue by chabgood** [Lurkki14/tuxclocker-cli#1]
tuxclocker-cli list 0 sensors
list
0
sensors
Error: no GPU with index 0

I have 4 - 2080's and 3 - 2080 supers in my system.

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2080    On   | 00000000:19:00.0 Off |                  N/A |
|  0%   51C    P2   160W / 225W |   3774MiB /  7982MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
|  0%   52C    P2   161W / 250W |   3780MiB /  7982MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:1B:00.0 Off |                  N/A |
|  0%   55C    P2   175W / 250W |   3780MiB /  7982MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 2080    On   | 00000000:1C:00.0 Off |                  N/A |
|  0%   48C    P2   149W / 225W |   3994MiB /  7979MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 2080    On   | 00000000:67:00.0 Off |                  N/A |
|  0%   48C    P2   166W / 225W |   3774MiB /  7982MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 2080    On   | 00000000:68:00.0 Off |                  N/A |
|  0%   48C    P2   179W / 225W |   3774MiB /  7982MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  On   | 00000000:69:00.0 Off |                  N/A |
|  0%   51C    P2   157W / 250W |   3780MiB /  7982MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by Lurkki14** [comment]
Sorry for the late response, but this repo is inactive. If you want TuxClocker with a CLI interface, please open an issue on https://github.com/Lurkki14/tuxclocker
